import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

// Lazy-initialized Gemini Client helper
let aiClient: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is missing. Please set it in Settings > Secrets.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Setup body parsers
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));

  // API Route: Health Check
  app.get("/api/health", (req, res) => {
    res.json({
      status: "ok",
      timestamp: new Date().toISOString(),
      platform: "BuildTrace India AI Engine",
      cvModel: "PyTorch YOLO-v8 Site Progress Network",
      bimEngine: "Three.js IFC Parser v2.1"
    });
  });

  // API Route: AI Progress & Discrepancy Analysis (Gemini integration)
  app.post("/api/ai/analyze", async (req, res) => {
    const { anomaly, customQuestion, context } = req.body;

    try {
      const client = getGeminiClient();
      
      const prompt = `
You are the Lead AI Construction Site Auditor & BIM Integration Expert for BuildTrace India, a computer-vision based progress monitoring platform.
A user is inspecting a specific drone-captured site progress anomaly or construction discrepancy.

Here is the context of the issue:
- Site/Project: Bangalore Tech Park Phase 2
- Location: ${context?.location || 'Zone B, 3rd Floor'}
- Element Type: ${context?.elementType || 'Slab Structural Reinforcement'}
- Discrepancy Detected: ${anomaly?.description || 'Rebar placement density is 15% lower than the BIM specification (IFC4).'}
- Current Progress Deviation: ${anomaly?.deviation || 'Critical Delay (Expected 100% completion, actual is 78%)'}
- Potential Cause: ${anomaly?.possibleCause || 'Supply chain mismatch or labor scheduling conflict'}

The user is asking:
"${customQuestion || 'Provide a detailed engineering impact report, root cause analysis, and a structured 3-step remediation workflow.'}"

Please compile a highly detailed, professional construction audit report. Include:
1. **Engineering Impact Analysis**: Assess structural integrity, scheduling, and sequencing risks (especially dependencies like plumbing/electrical/HVAC routing).
2. **Detailed Root Cause Analysis**: Explain how this discrepancy might have occurred in an Indian construction site context (e.g., procurement delays, site coordination issues, drawing misinterpretations).
3. **Structured Remediation Workflow**: Provide a step-by-step action plan to resolve the issue, update the BIM model, and re-inspect using CV/drone imagery.
4. **Predictive Analytics Advice**: Suggest preventive measures to ensure this anomaly does not repeat on higher floors.

Format your response in beautiful, clear Markdown, using bold headers and clean lists. Keep the tone professional, technical, and constructive.
`;

      const response = await client.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an expert Indian Construction Manager and BIM/Computer-Vision Site Auditor. Your goal is to provide highly precise, practical engineering advice for resolving discrepancies between actual site work (drone/360 camera) and digital BIM designs (IFC). Use clear, actionable steps.",
        }
      });

      res.json({
        success: true,
        report: response.text || "No analysis report was generated by the model.",
        modelUsed: "gemini-3.5-flash",
        analyzedAt: new Date().toISOString()
      });

    } catch (error: any) {
      console.error("Gemini API Error:", error);
      
      // Fallback response for missing API key or transient failures so the app stays functional & looks incredible
      const fallbackReport = `
### ⚠️ BuildTrace AI - Offline Inspection Report (Simulated)

The Live Gemini AI connection is currently using our offline backup engine. Below is an automated inspection and remediation protocol based on the selected anomaly parameters:

#### 1. Engineering Impact Analysis (Simulated)
* **Structural & Safety Risk:** The mismatch in ${context?.elementType || 'structural design'} represents a **High Risk** to structural loading. Immediate concrete pouring is suspended for this zone.
* **Sequencing Bottlenecks:** Downstream contractors (MEP, interior fit-outs) will be delayed by an estimated **5-7 working days** if concrete verification is not completed within 48 hours.
* **BIM Sync Status:** IFC model revision level is temporarily flagged as *OUT OF SYNC* in the local CDE (Common Data Environment).

#### 2. Root Cause Analysis
* **Coordination Gap:** Likely a discrepancy between the 2D shop drawings approved at the site level and the federated 3D BIM model in the central design office.
* **Material Discrepancy:** Potential supply bottleneck of standard Grade Fe550D TMT reinforcement bars, leading to unauthorized use of local alternatives or under-reinforcement.

#### 3. 3-Step Remediation Workflow
1. **Physical Stop-Work & Audit:** Issue an immediate digital **Non-Conformance Report (NCR)** via BuildTrace. Place a physical tag on the Zone.
2. **Re-Bar Realignment:** Install the missing reinforcement spacing elements as per IFC specs. Use hand-held 360-degree scanners to upload a localized point cloud for immediate validation.
3. **Vantage Photogrammetry Audit:** Schedule an ad-hoc drone progress capture. Run the alignment comparison pipeline (ICP) to verify progress before authorizing concrete pouring.

*To activate live, highly personalized expert advice, please ensure your **GEMINI_API_KEY** is configured in the Secrets panel.*
`;

      res.json({
        success: false,
        report: fallbackReport,
        modelUsed: "local-simulation-rules",
        error: error.message || "Failed to generate report"
      });
    }
  });

  // API Route: Simulated FastAPI Python Pipeline Log
  // Demonstrating photogrammetry processing logs
  app.get("/api/pipeline/logs", (req, res) => {
    const currentStep = Math.floor((Date.now() / 4000) % 5);
    const steps = [
      {
        step: "Data Ingestion",
        status: "Completed",
        log: "[INFO] FastAPI: Drone DJI Matrice 300 RTK orthomosaic chunk received. 42 high-res JPGs uploaded to AWS S3 storage. Triggered Celery task queue ID: cv-chunk-9938.",
        progress: 100
      },
      {
        step: "Photogrammetry Re-construction",
        status: currentStep === 1 ? "In Progress" : (currentStep > 1 ? "Completed" : "Pending"),
        log: currentStep === 1 
          ? "[PROCESS] Python/Open3D: Generating densified 3D point cloud. Matching keypoints using SIFT. RANSAC active iterations: 4500/5000..." 
          : (currentStep > 1 ? "[INFO] Python/Open3D: Dense point cloud successfully generated. Vertices: 12,450,230. Exported to PLY." : "[INFO] Awaiting previous stage."),
        progress: currentStep === 1 ? 65 : (currentStep > 1 ? 100 : 0)
      },
      {
        step: "BIM Alignment (IFC to Mesh)",
        status: currentStep === 2 ? "In Progress" : (currentStep > 2 ? "Completed" : "Pending"),
        log: currentStep === 2 
          ? "[PROCESS] Python/IFCOpenShell: Parsing IFC4 floor plan. Extracting structural bounding boxes. Executing Iterative Closest Point (ICP) algorithm for spatial alignment..." 
          : (currentStep > 2 ? "[INFO] Python/ICP: Spatial translation aligned. Mean Squared Error (MSE): 0.012m. Coordinate system synchronized with UTM Zone 43N." : "[INFO] Awaiting coordinate alignment."),
        progress: currentStep === 2 ? 40 : (currentStep > 2 ? 100 : 0)
      },
      {
        step: "Computer Vision Discrepancy Detection",
        status: currentStep === 3 ? "In Progress" : (currentStep > 3 ? "Completed" : "Pending"),
        log: currentStep === 3 
          ? "[PROCESS] Python/PyTorch: Running instance segmentation for electrical conduits, drywalls, and concrete rebars. Comparing detected bounding volumes with IFC coordinates..." 
          : (currentStep > 3 ? "[INFO] PyTorch: Detected 2 progress anomalies: 1) Slab reinforcement under-density in Zone B (85% installed), 2) Partition wall missing in Zone A." : "[INFO] Awaiting neural network forward pass."),
        progress: currentStep === 3 ? 80 : (currentStep > 3 ? 100 : 0)
      },
      {
        step: "Real-time Frontend Synchronization",
        status: currentStep === 4 ? "In Progress" : "Completed",
        log: currentStep === 4 
          ? "[PROCESS] Express: Pushing progress metrics update via WebSockets/SSE to React Dashboard. Reloading Three.js buffer geometry..." 
          : "[INFO] Express/Vite: Site state synced. Web dashboard loaded. Latency: 120ms.",
        progress: currentStep === 4 ? 90 : 100
      }
    ];

    res.json({
      timestamp: new Date().toISOString(),
      activeStepIndex: currentStep,
      pipelineSteps: steps
    });
  });

  // Serve static files / Vite middleware
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
