import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Sparkles, Clock, TrendingUp, AlertCircle, ShieldAlert, CheckCircle2, 
  ChevronDown, ChevronUp, ArrowRight, Gauge, Layers, Eye, RefreshCw, 
  UserCheck, AlertTriangle, ArrowUpRight, HelpCircle, Hammer, HelpCircle as HelpIcon,
  Activity, ListCollapse, ListTodo, Plus, Search, HelpCircle as InfoIcon
} from "lucide-react";

interface InsightCard {
  id: string;
  title: string;
  shortDesc: string;
  metric: string;
  metricUnit?: string;
  status: "critical" | "warning" | "success" | "info";
  icon: React.ReactNode;
}

export default function AIInsightsComponent() {
  const [expandedCard, setExpandedCard] = useState<string | null>("predicted-delay");
  const [resolvedRecommendationIds, setResolvedRecommendationIds] = useState<string[]>([]);
  const [filterTrade, setFilterTrade] = useState<string>("All");

  const toggleExpand = (id: string) => {
    if (expandedCard === id) {
      setExpandedCard(null);
    } else {
      setExpandedCard(id);
    }
  };

  const handleResolveRecommendation = (id: string) => {
    if (resolvedRecommendationIds.includes(id)) {
      setResolvedRecommendationIds(prev => prev.filter(item => item !== id));
    } else {
      setResolvedRecommendationIds(prev => [...prev, id]);
    }
  };

  const cards: InsightCard[] = [
    {
      id: "predicted-delay",
      title: "Predicted Delay Assessment",
      shortDesc: "Downstream delay hazards identified in L2 structural framing.",
      metric: "8 Days",
      metricUnit: "Est. Slip",
      status: "critical",
      icon: <Clock className="w-5 h-5 text-red-500" />
    },
    {
      id: "productivity",
      title: "Productivity & Velocity Engine",
      shortDesc: "Comparison of design pouring speeds vs daily scanning outputs.",
      metric: "94.2%",
      metricUnit: "Labor Index",
      status: "success",
      icon: <TrendingUp className="w-5 h-5 text-emerald-500" />
    },
    {
      id: "loose-ends",
      title: "Loose Ends & Incomplete Joints",
      shortDesc: "Unfinished structural ties and open weld plates needing attention.",
      metric: "12",
      metricUnit: "Open Items",
      status: "warning",
      icon: <Layers className="w-5 h-5 text-amber-500" />
    },
    {
      id: "missing-elements",
      title: "Missing Elements Ledger",
      shortDesc: "Specified IFC components completely omitted in scan feeds.",
      metric: "3",
      metricUnit: "Missing Components",
      status: "critical",
      icon: <AlertCircle className="w-5 h-5 text-red-500" />
    },
    {
      id: "risk-score",
      title: "RERA Risk Score Assessment",
      shortDesc: "Comprehensive schedule compliance rating calculated daily.",
      metric: "78 /100",
      metricUnit: "Compliance",
      status: "info",
      icon: <Gauge className="w-5 h-5 text-indigo-500" />
    },
    {
      id: "recommendations",
      title: "AI Action Recommendations",
      shortDesc: "Prescriptive remediation tasks generated by BuildTrace.",
      metric: "5",
      metricUnit: "Actions",
      status: "info",
      icon: <Sparkles className="w-5 h-5 text-indigo-500" />
    }
  ];

  const getStatusColor = (status: string, isBorder: boolean = false) => {
    switch (status) {
      case "critical":
        return isBorder ? "border-red-500/30 bg-red-50/40" : "bg-red-50 text-red-700 border-red-200";
      case "warning":
        return isBorder ? "border-amber-500/30 bg-amber-50/40" : "bg-amber-50 text-amber-700 border-amber-200";
      case "success":
        return isBorder ? "border-emerald-500/30 bg-emerald-50/40" : "bg-emerald-50 text-emerald-700 border-emerald-200";
      default:
        return isBorder ? "border-indigo-500/30 bg-indigo-50/40" : "bg-indigo-50 text-indigo-700 border-indigo-200";
    }
  };

  return (
    <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm flex flex-col gap-5 text-slate-800">
      
      {/* HEADER SECTION */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-5">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-indigo-50 text-indigo-600">
              <Sparkles className="w-4 h-4 text-indigo-600 animate-pulse" />
            </span>
            <h3 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider">
              Gemini AI-Powered Site Insights
            </h3>
          </div>
          <p className="text-xs text-slate-400">
            Real-time physical photogrammetry aligning IFC design coordinates with active risk indices.
          </p>
        </div>

        {/* Filter Trade Selector */}
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase font-mono">Filter Trade:</span>
          <div className="flex bg-slate-100 p-0.5 rounded-lg border border-slate-200">
            {["All", "Structure", "MEP", "Finishing"].map((trade) => (
              <button
                key={trade}
                onClick={() => setFilterTrade(trade)}
                className={`px-2 py-1 text-[10px] font-bold rounded-md transition ${
                  filterTrade === trade 
                    ? "bg-white text-slate-900 shadow-sm" 
                    : "text-slate-500 hover:text-slate-800"
                }`}
              >
                {trade}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* CORE INSIGHTS EXPANDABLE ACCORDION LIST */}
      <div className="grid grid-cols-1 gap-4">
        {cards.map((card) => {
          const isExpanded = expandedCard === card.id;
          
          return (
            <div
              key={card.id}
              className={`border rounded-xl transition-all duration-300 overflow-hidden ${
                isExpanded 
                  ? "border-indigo-500 shadow-md ring-2 ring-indigo-50" 
                  : "border-slate-200 hover:border-slate-350 bg-slate-50/30"
              }`}
            >
              {/* Card Header (Always Visible, Click to toggle) */}
              <div
                onClick={() => toggleExpand(card.id)}
                className="p-4 flex items-center justify-between gap-4 cursor-pointer select-none bg-white hover:bg-slate-50/50 transition-colors"
              >
                <div className="flex items-center gap-3.5 min-w-0">
                  <div className="p-2 bg-slate-50 rounded-lg border border-slate-150 shrink-0">
                    {card.icon}
                  </div>
                  <div className="min-w-0">
                    <h4 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider">
                      {card.title}
                    </h4>
                    <p className="text-[11px] text-slate-400 truncate max-w-sm sm:max-w-md">
                      {card.shortDesc}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4 shrink-0">
                  {/* Badge metric */}
                  <div className="text-right">
                    <span className="text-xs font-black text-slate-900 font-mono block">
                      {card.metric}
                    </span>
                    <span className="text-[9px] text-slate-400 font-mono block">
                      {card.metricUnit}
                    </span>
                  </div>

                  {/* Expand icon arrow */}
                  <span className="p-1 rounded-full bg-slate-100 text-slate-500 group-hover:bg-slate-200 transition-colors">
                    {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </span>
                </div>
              </div>

              {/* Card Expandable Body Content */}
              <AnimatePresence initial={false}>
                {isExpanded && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.25, ease: "easeInOut" }}
                    className="border-t border-slate-100 bg-slate-50/40"
                  >
                    <div className="p-5 text-xs text-slate-700 leading-relaxed">
                      {card.id === "predicted-delay" && <PredictedDelayDetail />}
                      {card.id === "productivity" && <ProductivityDetail />}
                      {card.id === "loose-ends" && <LooseEndsDetail />}
                      {card.id === "missing-elements" && <MissingElementsDetail />}
                      {card.id === "risk-score" && <RiskScoreDetail />}
                      {card.id === "recommendations" && (
                        <RecommendationsDetail 
                          resolvedIds={resolvedRecommendationIds}
                          onResolve={handleResolveRecommendation}
                        />
                      )}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>

      {/* FOOTER METRIC BANNER */}
      <div className="bg-slate-900 rounded-xl p-4 text-white flex flex-col md:flex-row justify-between items-center gap-4 relative overflow-hidden">
        <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[radial-gradient(#fff_1px,transparent_1px)] [background-size:16px_16px]" />
        
        <div className="flex items-center gap-3 relative z-10">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center border border-indigo-500/30 animate-pulse">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h5 className="text-[11px] font-extrabold uppercase tracking-wider text-indigo-300">
              Active Predictive Core Engine
            </h5>
            <p className="text-[9px] text-slate-400 mt-0.5">
              Analyzing 12,492 vertices across 5 structural slabs. Last synced 2 mins ago.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-4 relative z-10 text-[10px]">
          <span className="text-slate-400">RERA Fine Mitigation: <strong className="text-emerald-400 font-mono">₹4,80,000 Saved</strong></span>
          <span className="text-slate-600">|</span>
          <span className="text-slate-400">Downstream Clashes Cleared: <strong className="text-indigo-300 font-mono">14 Cleared</strong></span>
        </div>
      </div>

    </div>
  );
}

/* ==========================================
   1. PREDICTED DELAY DETAIL COMPONENT
   ========================================== */
function PredictedDelayDetail() {
  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <div className="bg-red-50/80 border border-red-200/50 rounded-lg p-3.5 text-red-800 leading-relaxed">
        <div className="flex items-center gap-2 font-extrabold text-[11px] uppercase tracking-wide text-red-700 mb-1">
          <ShieldAlert className="w-4 h-4 text-red-500" />
          Critical Path Schedule Slips Detected
        </div>
        <span>
          BuildTrace photogrammetry alignment algorithms show that the physical reinforcement casting on <strong>Level 2 Zone B Structural columns</strong> has been delayed by 6.2 days due to a rebar density mismatch. This creates a cascade effect of <strong>8.0 days slip</strong> for the L2 Ceiling Slab pour, directly impacting the target RERA compliance threshold.
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div className="bg-white border border-slate-150 rounded-lg p-3">
          <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider block">Delay Probability</span>
          <span className="text-base font-extrabold text-red-600 font-mono mt-1 block">94.8% High</span>
          <div className="w-full bg-slate-100 h-1 rounded-full overflow-hidden mt-2">
            <div className="bg-red-500 h-full w-[95%]" />
          </div>
        </div>
        <div className="bg-white border border-slate-150 rounded-lg p-3">
          <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider block">Cost Penalty Risk</span>
          <span className="text-base font-extrabold text-slate-800 font-mono mt-1 block">₹1,20,000</span>
          <span className="text-[8px] text-slate-400 mt-0.5 block">Estimated RERA daily levy</span>
        </div>
        <div className="bg-white border border-slate-150 rounded-lg p-3">
          <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider block">Downstream Impact</span>
          <span className="text-base font-extrabold text-amber-500 font-mono mt-1 block">3 Tasks Blocked</span>
          <span className="text-[8px] text-slate-400 mt-0.5 block">MEP Sleeves, Formwork, Finishes</span>
        </div>
      </div>

      <div className="border border-slate-150 rounded-lg p-3 bg-slate-50/50">
        <span className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider block mb-2">Predicted Schedule Forecast Chain</span>
        <div className="relative pl-4 border-l border-slate-200 space-y-3.5 my-2">
          <div className="relative">
            <span className="absolute -left-[20.5px] top-1 w-2.5 h-2.5 rounded-full bg-emerald-500 ring-4 ring-white" />
            <div className="flex justify-between font-mono text-[10px]">
              <span className="font-bold text-slate-800">Ground Slab Pour (Week 1)</span>
              <span className="text-emerald-600">COMPLETED - ON TIME</span>
            </div>
          </div>
          <div className="relative">
            <span className="absolute -left-[20.5px] top-1 w-2.5 h-2.5 rounded-full bg-red-500 ring-4 ring-white animate-pulse" />
            <div className="flex justify-between font-mono text-[10px]">
              <span className="font-bold text-slate-800">L1 Structural Columns (Week 2-3)</span>
              <span className="text-red-500">DELAYED (+6 Days)</span>
            </div>
          </div>
          <div className="relative opacity-60">
            <span className="absolute -left-[20.5px] top-1 w-2.5 h-2.5 rounded-full bg-slate-300 ring-4 ring-white" />
            <div className="flex justify-between font-mono text-[10px]">
              <span className="font-bold text-slate-800">L1 Ceiling Slab Pour (Week 4 Plan)</span>
              <span className="text-slate-500">FORECASTED SLIP (+8 Days)</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ==========================================
   2. PRODUCTIVITY & VELOCITY DETAIL
   ========================================== */
function ProductivityDetail() {
  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <div className="flex justify-between items-center bg-emerald-50 border border-emerald-150 rounded-lg p-3.5 text-emerald-800">
        <div className="flex-1">
          <div className="flex items-center gap-1.5 font-bold text-[11px] uppercase tracking-wide text-emerald-700 mb-1">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            Excellent Pour Rate in Zone A
          </div>
          <span>
            Labor and machinery productivity metrics are highly optimized. Concrete pouring speed for Ground level Zone A hit <strong>42 cubic meters / hour</strong>, exceeding the designed target threshold by +8.4%.
          </span>
        </div>
        <span className="text-2xl font-black text-emerald-600 font-mono pl-4">+8.4%</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Concrete velocity bar */}
        <div className="bg-white border border-slate-150 p-3 rounded-lg flex flex-col gap-2">
          <div className="flex justify-between font-bold text-[10px]">
            <span className="text-slate-500 uppercase">Concrete Pouring Velocity</span>
            <span className="text-indigo-600">42 m³/hr vs 38 m³/hr Plan</span>
          </div>
          <div className="w-full bg-slate-105 h-2.5 rounded-full overflow-hidden flex">
            <div className="bg-indigo-600 h-full" style={{ width: "88%" }} />
          </div>
          <p className="text-[9px] text-slate-400">Calculated based on 3D depth-map delta between scans 14 and 15.</p>
        </div>

        {/* Drywall partition velocity */}
        <div className="bg-white border border-slate-150 p-3 rounded-lg flex flex-col gap-2">
          <div className="flex justify-between font-bold text-[10px]">
            <span className="text-slate-500 uppercase">Drywall Stud Fastening Rate</span>
            <span className="text-emerald-600">112 m/day vs 100 m/day Plan</span>
          </div>
          <div className="w-full bg-slate-105 h-2.5 rounded-full overflow-hidden flex">
            <div className="bg-emerald-500 h-full" style={{ width: "94%" }} />
          </div>
          <p className="text-[9px] text-slate-400">Gypsum framing detection rates verified automatically using drone imagery.</p>
        </div>
      </div>

      <div className="bg-slate-50 border border-slate-150 p-3 rounded-lg text-[10.5px]">
        <span className="font-bold text-slate-700 block mb-1">AI Productivity Insight:</span>
        Labor deployment patterns are optimal, but raw concrete transit delays from the local batching yard (east sector road works) are capping maximum daily structural casting potential. Recommend rescheduling batch trucks to 4:00 AM slots.
      </div>
    </div>
  );
}

/* ==========================================
   3. LOOSE ENDS DETAIL COMPONENT
   ========================================== */
function LooseEndsDetail() {
  const openItems = [
    { id: "LE-104", zone: "Zone B Ceiling", trade: "MEP / Structural", item: "Weld plate anchor bolts on L1 beam sleeve", status: "Critical", daysOpen: 4 },
    { id: "LE-108", zone: "Zone A Columns", trade: "Structure", item: "Unbent tie wire ends on C4 column cage rebar", status: "Warning", daysOpen: 6 },
    { id: "LE-112", zone: "Zone B Floor", trade: "Plumbing", item: "Sleeve seal gasket completely unsealed around main stack riser", status: "Critical", daysOpen: 2 },
    { id: "LE-115", zone: "Zone A Corridor", trade: "Finishing", item: "Ground terminal alignment pins unfastened", status: "Minor", daysOpen: 1 }
  ];

  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <p className="text-slate-600">
        Loose ends are uncompleted auxiliary structural connections, structural tie wires, and weld interfaces detected in photogrammetry scans that are blockading subsequent inspections.
      </p>

      <div className="overflow-x-auto">
        <table className="w-full text-left border border-slate-150 rounded-lg overflow-hidden">
          <thead>
            <tr className="bg-slate-100 text-slate-500 font-extrabold text-[9px] uppercase border-b border-slate-150">
              <th className="p-2.5">ID</th>
              <th className="p-2.5">Zone</th>
              <th className="p-2.5">Trade</th>
              <th className="p-2.5">Open Discrepancy</th>
              <th className="p-2.5">Severity</th>
              <th className="p-2.5">Days Open</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-150 bg-white font-sans text-[10px]">
            {openItems.map((item) => (
              <tr key={item.id} className="hover:bg-slate-50/50">
                <td className="p-2.5 font-bold font-mono text-slate-900">{item.id}</td>
                <td className="p-2.5 text-slate-600">{item.zone}</td>
                <td className="p-2.5 text-slate-500">{item.trade}</td>
                <td className="p-2.5 font-medium text-slate-800">{item.item}</td>
                <td className="p-2.5">
                  <span className={`px-2 py-0.5 rounded text-[8px] font-extrabold uppercase ${
                    item.status === "Critical" 
                      ? "bg-red-50 text-red-700 border border-red-200/50" 
                      : item.status === "Warning"
                      ? "bg-amber-50 text-amber-700 border border-amber-200/50"
                      : "bg-blue-50 text-blue-700 border border-blue-200/50"
                  }`}>
                    {item.status}
                  </span>
                </td>
                <td className="p-2.5 font-mono text-slate-500 text-center">{item.daysOpen}d</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="bg-amber-50 border border-amber-150 text-amber-800 rounded-lg p-3 text-[10.5px] leading-relaxed flex items-start gap-2">
        <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
        <span>
          <strong>Downstream Block Alert:</strong> Welds plates <strong>LE-104</strong> in Zone B are physically blockading MEP crews from anchoring horizontal air duct channels. Resolving this will immediately unlock 3 pending services.
        </span>
      </div>
    </div>
  );
}

/* ==========================================
   4. MISSING ELEMENTS DETAIL COMPONENT
   ========================================== */
function MissingElementsDetail() {
  const missingItems = [
    { id: "IFC-0482", element: "Fire Sprinkler Sleeve B4", floor: "First Floor", planDate: "Oct 18, 2026", status: "Critical", spec: "Sleeve Dia 150mm" },
    { id: "IFC-0911", element: "Drywall Corner Stud C1", floor: "Ground Floor", planDate: "Oct 24, 2026", status: "Minor", spec: "Steel C-Stud 100mm" },
    { id: "IFC-1033", element: "Air Handler Vibration Pad", floor: "Roof", planDate: "Nov 02, 2026", status: "Warning", spec: "Neoprene Pad Spec A" }
  ];

  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <div className="bg-red-50/70 border border-red-250/55 rounded-lg p-3.5 text-red-800 leading-relaxed">
        <div className="flex items-center gap-1.5 font-bold text-[11px] uppercase tracking-wide text-red-700 mb-1">
          <AlertCircle className="w-4 h-4 text-red-500" />
          Specified IFC Elements Omitted in Physical Scans
        </div>
        <span>
          BuildTrace cross-references the spatial coordinates of each element in the IFC file. The 3 items logged below are present in the CAD model design layouts but are completely missing from recent computer-vision orthomosaic scans.
        </span>
      </div>

      <div className="space-y-2.5">
        {missingItems.map((item) => (
          <div key={item.id} className="bg-white border border-slate-150 hover:border-slate-300 p-3 rounded-lg flex items-center justify-between text-xs transition">
            <div className="flex items-start gap-2.5">
              <span className="p-1.5 rounded bg-slate-50 border border-slate-150 text-slate-500 font-mono text-[9px] font-bold">
                IFC
              </span>
              <div>
                <span className="font-extrabold text-slate-850 block">{item.element}</span>
                <span className="text-[10px] text-slate-400 mt-0.5 block font-mono">
                  Floor: {item.floor} • Plan Date: {item.planDate} • Size: {item.spec}
                </span>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <span className={`px-2 py-0.5 rounded text-[8px] font-extrabold uppercase font-mono border ${
                item.status === "Critical" 
                  ? "bg-red-50 text-red-700 border-red-200" 
                  : "bg-amber-50 text-amber-700 border-amber-200"
              }`}>
                {item.status} Omitted
              </span>
              <button 
                className="p-1 text-indigo-600 hover:text-indigo-800 hover:bg-slate-50 rounded"
                title="View spatial coordinate in IFC 3D"
              >
                <ArrowUpRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ==========================================
   5. RISK SCORE DETAIL COMPONENT
   ========================================== */
function RiskScoreDetail() {
  const sectors = [
    { name: "Structural Integrity Compliance", score: "96%", status: "Excellent", color: "bg-emerald-500" },
    { name: "MEP Coordination & Clashes", score: "64%", status: "Critical Risk", color: "bg-red-500" },
    { name: "Slab Curing Rigidity Rate", score: "99%", status: "Excellent", color: "bg-emerald-500" },
    { name: "RERA Milestone Target Lag", score: "72%", status: "Warning", color: "bg-amber-500" }
  ];

  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <div className="flex flex-col md:flex-row items-center justify-between gap-5 bg-white border border-slate-150 p-4.5 rounded-lg">
        
        {/* Radial Gauge */}
        <div className="relative w-28 h-28 flex items-center justify-center shrink-0">
          <svg className="w-full h-full transform -rotate-90">
            <circle
              cx="56"
              cy="56"
              r="48"
              className="stroke-slate-100"
              strokeWidth="7"
              fill="transparent"
            />
            <circle
              cx="56"
              cy="56"
              r="48"
              className="stroke-indigo-600 transition-all duration-500"
              strokeWidth="9"
              strokeDasharray={`${2 * Math.PI * 48}`}
              strokeDashoffset={`${2 * Math.PI * 48 * (1 - 78 / 100)}`}
              strokeLinecap="round"
              fill="transparent"
            />
          </svg>
          <div className="absolute text-center">
            <span className="text-xl font-black text-slate-850 font-mono block leading-none">78</span>
            <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider block mt-1">Compliance</span>
          </div>
        </div>

        {/* Narrative */}
        <div className="flex-1 text-xs text-slate-600 leading-relaxed space-y-2">
          <h5 className="font-extrabold text-slate-900 uppercase text-[10px] tracking-wider">
            BuildTrace Risk Audit Evaluation
          </h5>
          <p>
            The project's composite risk rating is computed at <strong>78 out of 100</strong>. While structural foundation integrity scores remain flawless (96%), critical coordination clashes in the MEP sector (HVAC vs sprinkler spatial lines) have dragged down overall project velocity, invoking moderate RERA milestone penalty risks.
          </p>
          <div className="bg-slate-50 border border-slate-200 rounded p-2 text-[10px] font-mono text-slate-500 flex justify-between">
            <span>Critical Path Stability Index:</span>
            <span className="text-indigo-600 font-extrabold">MODERATE STABILIZATION</span>
          </div>
        </div>
      </div>

      {/* Sector breakdown bars */}
      <div className="space-y-3.5 mt-2">
        <span className="text-[9.5px] font-extrabold text-slate-400 uppercase tracking-wider block font-mono">Detailed Compliance Vectors</span>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {sectors.map((sec) => (
            <div key={sec.name} className="bg-slate-50 p-3 rounded-lg border border-slate-150 flex flex-col gap-1 text-[11px]">
              <div className="flex justify-between font-semibold">
                <span className="text-slate-700">{sec.name}</span>
                <span className="font-bold text-slate-900 font-mono">{sec.score}</span>
              </div>
              <div className="w-full bg-slate-200 h-1.5 rounded-full overflow-hidden mt-1">
                <div className={`${sec.color} h-full rounded-full`} style={{ width: sec.score }} />
              </div>
              <span className={`text-[8.5px] font-bold font-mono uppercase mt-1 ${
                sec.color === "bg-red-500" ? "text-red-600" : sec.color === "bg-amber-500" ? "text-amber-600" : "text-emerald-600"
              }`}>
                {sec.status}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ==========================================
   6. RECOMMENDATIONS DETAIL COMPONENT
   ========================================== */
interface RecommendationsDetailProps {
  resolvedIds: string[];
  onResolve: (id: string) => void;
}

function RecommendationsDetail({ resolvedIds, onResolve }: RecommendationsDetailProps) {
  const recommendations = [
    {
      id: "REC-01",
      title: "MEP Routing Adjustment (Zone B)",
      trade: "MEP / HVAC",
      action: "Reroute Zone B secondary sprinkler pipeline offset -40mm south to avoid the main air duct collision.",
      urgency: "Immediate Action Required",
      reward: "Unlocks drywall assembly for 12 corridor rooms"
    },
    {
      id: "REC-02",
      title: "Concrete Casting Hold & Audit",
      trade: "Structure",
      action: "Execute manual rebar spacing inspection on column C4 before pouring concrete formwork.",
      urgency: "Preventive Warning",
      reward: "Saves ₹8,00,000 structural rework costs"
    },
    {
      id: "REC-03",
      title: "Batch Truck Rescheduling",
      trade: "Logistics",
      action: "Shift ready-mix concrete truck transit windows from noon slots to early morning (4:00 AM) window to bypass highway work zone jams.",
      urgency: "Operational Opt",
      reward: "Accelerates daily concrete pour speeds by +14%"
    }
  ];

  return (
    <div className="flex flex-col gap-4 animate-fade-in">
      <p className="text-slate-600">
        AI-generated action steps are generated by correlating IFC structural coordinate nodes, RERA deadlines, and daily drone spatial feeds.
      </p>

      <div className="flex flex-col gap-3">
        {recommendations.map((rec) => {
          const isResolved = resolvedIds.includes(rec.id);
          
          return (
            <div 
              key={rec.id} 
              className={`border rounded-lg p-4 transition-all duration-300 flex flex-col justify-between gap-3 ${
                isResolved 
                  ? "bg-emerald-50/40 border-emerald-300/60 opacity-75" 
                  : "bg-white border-slate-150 hover:border-slate-350"
              }`}
            >
              <div className="flex justify-between items-start gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-[9px] text-slate-400 font-bold uppercase tracking-wider block">
                      {rec.id} • {rec.trade}
                    </span>
                    <span className={`px-1.5 py-0.2 rounded text-[8px] font-bold uppercase ${
                      rec.urgency.includes("Immediate") 
                        ? "bg-red-50 text-red-600 border border-red-100" 
                        : "bg-amber-50 text-amber-600 border border-amber-100"
                    }`}>
                      {rec.urgency}
                    </span>
                  </div>
                  
                  <h5 className="font-bold text-slate-850 mt-1 leading-snug">
                    {rec.title}
                  </h5>
                  
                  <p className="text-slate-600 mt-1.5 text-[11px] leading-relaxed">
                    {rec.action}
                  </p>
                </div>

                <button 
                  onClick={() => onResolve(rec.id)}
                  className={`px-3 py-1.5 rounded-lg text-[10px] font-bold transition whitespace-nowrap border shrink-0 ${
                    isResolved
                      ? "bg-emerald-600 text-white border-emerald-700 hover:bg-emerald-700"
                      : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                  }`}
                >
                  {isResolved ? "✓ Implemented" : "Implement Task"}
                </button>
              </div>

              <div className="border-t border-slate-100/80 pt-2 flex items-center justify-between text-[10px] text-slate-400">
                <span className="flex items-center gap-1">
                  <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
                  Benefit: <strong className="text-indigo-600 font-sans">{rec.reward}</strong>
                </span>
                <span className="text-[9px] font-mono font-bold text-slate-400 uppercase">
                  CONFIDENCE: 98.4%
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
